### ISSUE TITLE
An option to allow "unknown" assertion

### ISSUE THREAD

**Issue by ilyub** [Dremora/eslint-plugin-no-type-assertion#2]
Hi,

Thank you for the plugin.

Is it possible to add an option to allow "unknown" assertion?

1. "unknown" assertion is safe.
2. In some cases, you need to cast "any" to "unknown" to avoid eslint warnings.

**Comment by Dremora** [comment]
I haven't previously found a need for this, but I can't think why such assertions wouldn't be safe. This is now available in 1.3.0.

**Comment by ilyub** [comment]
thx for the update
